CREATE TABLE strongly_sets(
    db_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id UUID PRIMARY KEY NOT NULL,
    weight INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    exercise_id UUID REFERENCES strongly_exercises(id) ON DELETE CASCADE NOT NULL,
    workout_id UUID REFERENCES strongly_workouts(id) ON DELETE CASCADE NOT NULL
);