CREATE TABLE strongly_sets(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    set_number INTEGER NOT NULL,
    weight INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    exercise_id INTEGER REFERENCES strongly_exercises(id) ON DELETE CASCADE NOT NULL,
    workout_id INTEGER REFERENCES strongly_workouts(id) ON DELETE CASCADE NOT NULL
);