CREATE TABLE strongly_users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    fullname TEXT NOT NULL,
    password TEXT NOT NULL,
    nickname TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP
);

ALTER TABLE strongly_workouts
    ADD COLUMN
        user_id INTEGER REFERENCES strongly_users(id) ON DELETE SET NULL;

ALTER TABLE strongly_exercises
    ADD COLUMN
        user_id INTEGER REFERENCES strongly_users(id) ON DELETE SET NULL;

ALTER TABLE strongly_sets
    ADD COLUMN
        user_id INTEGER REFERENCES strongly_users(id) ON DELETE SET NULL;