INSERT INTO strongly_exercises(title, workout_id)
VALUES
    (
            'Squat',
            1
        ),
        (
            'Bench',
            1
        ),
        (
            'Rows',
            1
        ),
        (
            'Squat',
            2
        ),
        (
            'Overhead Press',
            2
        ),
        (
            'Deadlift',
            2
        ),
        (
            'Squat',
            3
        ),
        (
            'Bench',
            3
        ),
        (
            'Rows',
            3
        );

